[package]
name = "sanakirja"
version = "0.1.0"
authors = ["Pierre-Ã‰tienne Meunier"]
build = "build.rs"
license = "MPL-2.0"

[dependencies]
libc="*"
log="*"
env_logger="*"
fs2="*"

[build-dependencies]
libc="*"
